let showall = document.querySelector('.all')
let section = document.querySelector('.section')
let doll1 = document.querySelector('.doll1')
let doll2 = document.querySelector('.doll2')
let doll3 = document.querySelector('.doll3')
let doll4 = document.querySelector('.doll4')
let tecno = document.querySelector('.tecno')
let apple = document.querySelector('.apple')
let samsung = document.querySelector('.samsung')
let infinix = document.querySelector('.infinix')
let un1 = document.querySelector('.un1')
let un2 = document.querySelector('.un2')
let un3 = document.querySelector('.un3')
let un4 = document.querySelector('.un4')
let products = [
    {   Price:'Price',
        Brand: 'Infinix',
        Model:'Hot9',
        Price:'100',
        Quantity:'100'
        
    },
    {
        Brand: 'Tecno',
        Model:'Spark 9',
        Price:'200',
        Quantity:'200'
        
    },
    {
        Brand: 'Samsung',
        Model:'Galaxy J6',
        Price:'300',
        Quantity:'300'
        
    },
    {
        Brand: 'Apple',
        Model:'Iphone 14',
        Price:'1200',
        Quantity:'1000'
    }
]
doll3.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section2').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[2].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Quantity + '</li>';
    
})
samsung.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section2').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[2].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Quantity + '</li>';
    
})
un3.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section2').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[2].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Quantity + '</li>';
    
})
doll4.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section3').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Quantity + '</li>';
})
apple.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section3').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Quantity + '</li>';
})
un4.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section3').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Quantity + '</li>';
})
tecno.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section1').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[1].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Quantity + '</li>';
})
doll2.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section1').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[1].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Quantity + '</li>';
})
un2.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section1').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[1].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Quantity + '</li>';
})
doll1.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[0].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Quantity + '</li>';
})
infinix.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[0].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Quantity + '</li>';
})
un1.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[0].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Quantity + '</li>';
})
showall.addEventListener('click', function(){
    document.querySelector('#top').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Brand' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center; width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Model' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Price($)' + '</li>' + '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;font-weight:900">' + 'Quantity(Units)' + '</li>';
    document.querySelector('#section').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[0].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[0].Quantity + '</li>';
    document.querySelector('#section1').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[1].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[1].Quantity + '</li>';
    document.querySelector('#section2').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[2].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[2].Quantity + '</li>';
    document.querySelector('#section3').innerHTML = '<li style="border:1px solid black;list-style-type:none;text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Brand + '</li>'+ '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px;">' + products[3].Model + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Price + '</li>' + '<li style="border:1px solid black;list-style-type:none; text-align:center;width:100%;height:50px;display:flex;justify-content:center;align-items:center;;height:50px">' + products[3].Quantity + '</li>';
})